### ISSUE TITLE
reset.css中有三个类名不知道是什么意思

### ISSUE THREAD

**Issue by cooper1x** [o2team/guide#9]
```CSS
ins { text-decoration: underline; }
del { text-decoration: line-through; }
mark { background: none; }
```
